version: 2
updates:
  - package-ecosystem: "npm"
    directory: "/"
    schedule:
      interval: "weekly"
      day: "monday"
    target-branch: "main"
    labels:
      - "dependencies 🔁"
    assignees:
      - "pcaversaccio"
    groups:
      npm-dependencies:
        patterns:
          - "*"

  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "weekly"
      day: "monday"
    target-branch: "main"
    labels:
      - "dependencies 🔁"
    assignees:
      - "pcaversaccio"
    groups:
      github-actions-dependencies:
        patterns:
          - "*"
