name: "Bug Report"
description: "Report a bug for snekmate."
title: "[Bug-Candidate]: "
labels:
  - bug
assignees:
  - pcaversaccio
body:
  - attributes:
      value: |
        Please check the [issues tab](https://github.com/pcaversaccio/snekmate/issues) to avoid duplicates.
        Thanks for taking the time to fill out this bug report!
    type: markdown
  - attributes:
      label: "Describe the issue:"
    id: what-happened
    type: textarea
    validations:
      required: true
  - attributes:
      description: "It can be a GitHub repository/gist or a simple code snippet."
      label: "Code example to reproduce the issue:"
      placeholder: "```vy\n@external\ndef\n```"
    id: reproduce
    type: textarea
    validations:
      required: true
  - attributes:
      description: |
        What version of Vyper are you running? 
        Run `vyper --version`
      label: "Version:"
    id: version
    type: textarea
    validations:
      required: true
  - attributes:
      description: |
        Please copy and paste any relevant log output. This 
        will be automatically formatted into code, so no need for backticks.
      render: shell
      label: "Relevant log output:"
    id: logs
    type: textarea
