name: 👁️ Halmos symbolic tests

on:
  push:
  pull_request:
  workflow_dispatch:
  schedule:
    - cron: "30 3 * * *"

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

permissions: {}

jobs:
  halmos:
    runs-on: ${{ matrix.os }}
    timeout-minutes: 90
    permissions:
      contents: read
    strategy:
      matrix:
        os:
          - ubuntu-latest
        python_version:
          - 3.14
        architecture:
          - x64
        halmos:
          - "--config test/halmos.toml"

    steps:
      - name: Checkout
        uses: actions/checkout@9c091bb21b7c1c1d1991bb908d89e4e9dddfe3e0 # v7.0.0
        with:
          submodules: recursive
          persist-credentials: false

      - name: Setup Python
        uses: actions/setup-python@ece7cb06caefa5fff74198d8649806c4678c61a1 # v6.3.0
        with:
          python-version: ${{ matrix.python_version }}
          architecture: ${{ matrix.architecture }}

      - name: Install Vyper
        run: python -m pip install git+https://github.com/vyperlang/vyper.git@master

      - name: Show the Vyper version
        run: vyper --version

      - name: Install Foundry
        uses: foundry-rs/foundry-toolchain@b00af27efadbc7b4ca8b82abbd903b17cc874d2a # v1.9.0
        with:
          version: nightly

      - name: Install `setuptools`
        run: python -m pip install setuptools==83.0.0

      - name: Install Halmos
        run: python -m pip install git+https://github.com/a16z/halmos.git@main

      - name: Show the Halmos version
        run: halmos --version

      - name: Install the Yices 2 SMT solver
        run: |
          set -Eeuo pipefail
          wget -q https://github.com/SRI-CSL/yices2/releases/download/yices-2.7.0/yices-2.7.0-x86_64-pc-linux-gnu-static-gmp.tar.gz
          echo "49566b6f817692820538df78fe406878400d79810631c9372b2495bc81d3e00a yices-2.7.0-x86_64-pc-linux-gnu-static-gmp.tar.gz" | sha256sum -c -
          sudo tar -xzf yices-2.7.0-x86_64-pc-linux-gnu-static-gmp.tar.gz --strip-components=2 -C /usr/local/bin yices-2.7.0/bin
          rm yices-2.7.0-x86_64-pc-linux-gnu-static-gmp.tar.gz

      - name: Install the Bitwuzla SMT solver
        run: |
          set -Eeuo pipefail
          wget -q https://github.com/bitwuzla/bitwuzla/releases/download/0.8.2/Bitwuzla-Linux-x86_64-static.zip
          echo "aa09f2b45f96695f9f755e8371c1b362915a870cc0f3bc3585ed7e236e088b7b Bitwuzla-Linux-x86_64-static.zip" | sha256sum -c -
          unzip -q Bitwuzla-Linux-x86_64-static.zip
          sudo mv Bitwuzla-Linux-x86_64-static/bin/* /usr/local/bin/
          rm -rf Bitwuzla-Linux-x86_64-static.zip Bitwuzla-Linux-x86_64-static

      - name: Prioritise the system binaries in `PATH`
        run: echo "/usr/local/bin" >> $GITHUB_PATH

      - name: Show the Yices 2 SMT solver version
        run: yices-smt2 --version

      - name: Show the Bitwuzla SMT solver version
        run: bitwuzla --version

      - name: Install `jsi`
        run: python -m pip install just-solve-it==0.1.2

      - name: Show the Foundry Halmos config
        run: forge config
        env:
          FOUNDRY_PROFILE: halmos
          FOUNDRY_DISABLE_NIGHTLY_WARNING: "1"

      - name: Run Halmos ERC-20 symbolic tests
        run: halmos --contract ERC20TestHalmos ${{ matrix.halmos }}
        env:
          FOUNDRY_PROFILE: halmos
          FOUNDRY_DISABLE_NIGHTLY_WARNING: "1"

      - name: Run Halmos ERC-721 symbolic tests
        run: halmos --contract ERC721TestHalmos ${{ matrix.halmos }}
        env:
          FOUNDRY_PROFILE: halmos
          FOUNDRY_DISABLE_NIGHTLY_WARNING: "1"

      - name: Run Halmos ERC-1155 symbolic tests
        run: halmos --contract ERC1155TestHalmos ${{ matrix.halmos }}
        env:
          FOUNDRY_PROFILE: halmos
          FOUNDRY_DISABLE_NIGHTLY_WARNING: "1"

      - name: Run Halmos math symbolic tests
        run: halmos --contract MathTestHalmos ${{ matrix.halmos }}
        env:
          FOUNDRY_PROFILE: halmos
          FOUNDRY_DISABLE_NIGHTLY_WARNING: "1"
